version: '3.8'

services:
  db:
    image: postgres:13
    container_name: notes_db
    env_file:

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      - notesapp-network

  migrate:
    image: migrate/migrate
    container_name: migrate
    command: [
      "-path", "/migrations",
      "-database", "postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable",
      "up"
    ]
    volumes:
      - ./db/migrations:/migrations
    depends_on:
      - db
    networks:
      - notesapp-network

networks:
  notesapp-network:
    driver: bridge
