app:
  name: "notes_app"
  port: 8080
  env: "development"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "notes_db"
  sslmode: "disable"

logger:
  level: "debug"
  file: "logs/app.log"