app:
  name: "notes_app"
  port: 8080
  env: "development"

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  dbname: ${DB_NAME}
  sslmode: "disable"

logger:
  level: "debug"
  file: "logs/app.log"